# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Setup python   
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    # Install dependencies    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    # Pull DVC
    - name: Pull DVC
      run: |
        dvc remote modify myremote gdrive_use_service_account false
        dvc remote modify myremote gdrive_use_service_account true
        dvc pull
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      
    # Lint with flake8    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Test with pytest
    - name: Test with pytest
      run: |
        python -m pytest


  # Deploy job on Render
  deploy:
    name: Deploy to Render
    needs: [build] # builds must pass to deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Move files to deployment directory
        run: |
          mkdir -p /opt/render/project/src/model
          mv model/*.pkl /opt/render/project/src/model/
          # Ensure the directory structure is as expected
          echo "Listing files in the deployment directory:"
          ls -l /opt/render/project/src/
          
      - name: Trigger deployment
        uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}  # Found in the render service url
          apiKey: ${{ secrets.RENDER_API_KEY }}  # Render Dashboard Account Settings
