# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Setup python   
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    # Install dependencies    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Install DVC
    - name: Install dvc-gdrive
      run: |
        pip install 'dvc[gdrive]'

    # Write Google Drive service account credentials to file
    - name: Configure DVC for Google Drive
      run: |
        dvc remote modify myremote gdrive_use_service_account true
        dvc remote modify myremote gdrive_service_account "${{ secrets.GDRIVE_CREDENTIALS_DATA }}"
      
    # Configure DVC to use Google Drive with the service account
    - name: Configure DVC for Google Drive
      run: |
        dvc remote modify myremote gdrive_use_service_account true
        dvc remote modify myremote gdrive_service_account_json_path gdrive-credentials.json

    # Pull DVC data
    - name: Pull DVC
      run: dvc pull

    # Lint with flake8    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Test with pytest
    - name: Test with pytest
      run: |
        python -m pytest
